apiVersion: v1
kind: Secret
metadata:
  name: vault
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  {{- range $key, $val := .Values.vault }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}