{{- if .Values.coreapi.ingress.enabled -}}
{{- $fullName := include "app.name" . -}}
{{- $svcPort := .Values.coreapi.service.port -}}
{{- $paths := .Values.coreapi.ingress.paths -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "app.name" . }}
  namespace: {{ .Values.namespace }}
  {{- with .Values.coreapi.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.coreapi.ingress.tls }}
  tls:
  {{- range .Values.coreapi.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.coreapi.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
  {{- range $p := $paths }}
          - path: {{ $p }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
        {{- end }}
  {{- end }}
{{- end }}

