apiVersion: v1
kind: ConfigMap
metadata:
  name: common-core
  namespace: {{ .Values.namespace }}
data:
  {{- range $key, $val := .Values.configmap }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}