apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.name" . }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.coreapi.service.type }}
  ports:
    - port: {{ .Values.coreapi.service.port }}
      targetPort: {{ .Values.coreapi.service.targetport }}
      protocol: TCP
      name: http
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}

