apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postit.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.postit.service.type }}
  clusterIP: None
  selector:
    {{- include "app.postitselectorLabels" . | nindent 4 }}
  sessionAffinity: None


